[build]
  publish = "src"
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https://www.gstatic.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.gstatic.com; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self' https://*.firebaseio.com https://*.cloudfunctions.net wss://*.firebaseio.com; frame-ancestors 'none';"
    Cache-Control = "public, max-age=0, must-revalidate"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
