[[headers]]
  for = "/*"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdnjs.cloudflare.com 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; connect-src 'self' https://*.netlify.app https://*.firebaseio.com https://*.googleapis.com; frame-ancestors 'none';"
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.0.0"