[build]
  publish = "public"

[[redirects]]
  from = "/student/*"
  to = "/student/index.html"
  status = 200

[[redirects]]
  from = "/teacher/*"
  to = "/teacher/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/student/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval';"