[build]
  base = "/"
  publish = "public"
  command = "# no build command needed"

[[redirects]]
  from = "/student/*"
  to = "/student/index.html"
  status = 200

[[redirects]]
  from = "/teacher/*"
  to = "/teacher/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/student/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; connect-src 'self' https://*.firebase.io https://*.firebaseapp.com; script-src 'self' 'unsafe-inline' https://*.firebaseapp.com; frame-src 'self' https://*.firebaseapp.com"
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"