[build]
  base = "/"
  publish = "public"
  command = "# no build command needed"

[[redirects]]
  from = "/student/*"
  to = "/student/index.html"
  status = 200

[[redirects]]
  from = "/teacher/*"
  to = "/teacher/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/student/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = """
      default-src 'self';
      img-src 'self' data:;
      style-src 'self' 'unsafe-inline';
      script-src 'self' 'unsafe-inline' https://*.firebaseapp.com https://www.gstatic.com;
      connect-src 'self' https://*.firebaseio.com https://*.firebaseapp.com;
      frame-src 'self' https://*.firebaseapp.com https://app.netlify.com;
      worker-src 'self' blob:
    """
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"