[build]
  publish = "dist"

[[headers]]
  for = "/"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    X-Content-Type-Options = "nosniff"
    # Enlève les en-têtes non nécessaires
    Content-Security-Policy = "frame-ancestors 'none'"
    # Cache adapté pour la page principale
    Cache-Control = "no-store"

[[headers]]
  for = "/assets/*"
  [headers.values]
    # Cache optimisé pour les ressources statiques
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200